package QuanLy;

import DangNhapBanDau.DangNhapForm;
import Data.RoomModify;
import Data.DatThuePhongModify;
import static Data.DatThuePhongModify.TraCuuDSChiTietPhietDat;
import static QuanLy.QuanLyPhong.sodo;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.table.DefaultTableModel;
import qlks.CTDL.CTPhieuDat;
import qlks.CTDL.CTThue;
import qlks.CTDL.DanhSachPhong;
import qlks.CTDL.KhachHang;
import qlks.CTDL.NhanVien;
import qlks.CTDL.PhieuDat;
import qlks.CTDL.PhieuThue;
import qlks.CTDL.Phong;
import qlks.CTDL.ThongTinThuePhong;

public class FormXemPhieuDat_Va_ThuePhong extends javax.swing.JFrame {
    
    private static int table_Click_Row = -1;
    private static KhachHang khachThuePhongNay;
    private static NhanVien nvDangTruc;
    private static PhieuDat phieuDatPhongNay;
    public static int maPhieuDat = -1;
    private static CTThue ct_thuePhongNay;
    private static DanhSachPhong dsPhong;
    
    private static ArrayList<Phong> danhSachPhongTrongSql;

    public FormXemPhieuDat_Va_ThuePhong() {
        initComponents();
        this.nvDangTruc = DangNhapForm.nhanVienDangDangNhap;
        this.setTitle("Xem Thông Tin Phiếu Đặt [" + maPhieuDat + "]");
        jLabelMaPhieuDat.setText(""+maPhieuDat);
        jLabelMaNhanVien.setText(nvDangTruc.getMaNV());
        
        BatTXT(false);
    }
    // TRƯỜNG HỢP PHÒNG NÀY CHƯA ĐẶT
    public FormXemPhieuDat_Va_ThuePhong(int maphieudat){//, NhanVien nhanvien) {
        this.maPhieuDat = maphieudat;
        initComponents();
        this.nvDangTruc = DangNhapForm.nhanVienDangDangNhap;
        this.setTitle("Xem Thông Tin Phiếu Đặt [" + maPhieuDat + "]");
        jLabelMaPhieuDat.setText(""+maPhieuDat);
        jLabelMaNhanVien.setText(nvDangTruc.getMaNV());
        danhSachPhongTrongSql = RoomModify.layDanhSachPhong();
        BatTXT(false);
        loadThongTinDat();
        loadDSPhongRaTable();
        
    }
    private void loadThongTinDat()
    {
       dsPhong = TraCuuDSChiTietPhietDat(maPhieuDat);
       if(dsPhong.dsCTDat.isEmpty())
       {
           
                if(JOptionPane.showConfirmDialog(null, "Phiếu Đặt này Không Có Chi Tiết Đặt!\n Hủy bỏ?", "Thông Báo", JOptionPane.YES_NO_OPTION) == 0)
                        DatThuePhongModify.HuyBoPhietDat(maPhieuDat);
                this.setVisible(false);
       }
       khachThuePhongNay = DatThuePhongModify.TimKhach(dsPhong.getPhieudat().getMaKH());
       txt_MaKH.setText(khachThuePhongNay.getCMND());
       txt_DiaChiKhachHang.setText(khachThuePhongNay.getDiaChi());
       txt_HoTenKH.setText(khachThuePhongNay.getHo()+" " +khachThuePhongNay.getTen());
       txt_SDT_KH.setText(khachThuePhongNay.getSDT());
       txt_MaSoThueKH.setText(khachThuePhongNay.getMaSoThue());
       txt_NgayDen.setText(dsPhong.dsCTDat.get(0).getNgayDen().toString());
       txt_NgayDi.setText(dsPhong.dsCTDat.get(0).getNgayDi().toString());
       
       
       
    }
    private void BatTXT(boolean t)
    {
            txt_MaKH.setEditable(t);
            txt_HoTenKH.setEditable(t);
            txt_DiaChiKhachHang.setEditable(t);
            txt_MaSoThueKH.setEditable(t);
            txt_SDT_KH.setEditable(t);
            txt_NgayDen.setEditable(t);
            txt_NgayDi.setEditable(t);
            
        
    }
    private void loadDSPhongRaTable()
    {
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã lPhòng");
        model.addColumn("Hạng Phòng");
        Vector vec;
        Phong phong;
        for(CTPhieuDat phieu: dsPhong.dsCTDat)
        {
                vec = new Vector();
                vec.add(phieu.getMaPhong());
                phong = RoomModify.TimPhong(phieu.getMaPhong(), danhSachPhongTrongSql);
                vec.add(phong.getHangPhong());
                model.addRow(vec);                
        }
        
        jTable_DsPhongDaChon.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNenFrame = new javax.swing.JPanel();
        jPanelThongTinPhong2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanelThongTinKhachHang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_MaKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_HoTenKH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_SDT_KH = new javax.swing.JTextField();
        txt_MaSoThueKH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelThongBao = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelMaNhanVien = new javax.swing.JLabel();
        jLabelMaPhieuDat = new javax.swing.JLabel();
        jButton_Check = new javax.swing.JButton();
        txt_DiaChiKhachHang = new javax.swing.JTextField();
        txt_NgayDi = new javax.swing.JTextField();
        txt_NgayDen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DsPhongDaChon = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Lập Phiếu Thuê Phòng");
        setBackground(new java.awt.Color(153, 153, 255));
        setResizable(false);

        jPanelNenFrame.setBackground(new java.awt.Color(102, 153, 255));
        jPanelNenFrame.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelNenFrame.setPreferredSize(new java.awt.Dimension(645, 620));

        jPanelThongTinPhong2.setBackground(new java.awt.Color(153, 204, 255));
        jPanelThongTinPhong2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Hành động", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 51))); // NOI18N
        jPanelThongTinPhong2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelThongTinPhong2.setPreferredSize(new java.awt.Dimension(560, 580));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Lập Phiếu Thuê");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Hủy Phiếu Đặt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelThongTinPhong2Layout = new javax.swing.GroupLayout(jPanelThongTinPhong2);
        jPanelThongTinPhong2.setLayout(jPanelThongTinPhong2Layout);
        jPanelThongTinPhong2Layout.setHorizontalGroup(
            jPanelThongTinPhong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinPhong2Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(jPanelThongTinPhong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelThongTinPhong2Layout.setVerticalGroup(
            jPanelThongTinPhong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThongTinPhong2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelThongTinKhachHang.setBackground(new java.awt.Color(153, 204, 255));
        jPanelThongTinKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 51))); // NOI18N
        jPanelThongTinKhachHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelThongTinKhachHang.setPreferredSize(new java.awt.Dimension(477, 320));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mã KH(CMND):");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Họ&tên:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("SĐT:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Địa Chỉ:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Mã số thuế:");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabelThongBao.setForeground(new java.awt.Color(255, 0, 0));
        jLabelThongBao.setText("Thông báo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelThongBao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelThongBao)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Mã Phiếu Đặt:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Mã Nhân Viên: ");

        jLabelMaNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMaNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelMaNhanVien.setText("01");

        jLabelMaPhieuDat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMaPhieuDat.setText("---[Trống]---");

        jButton_Check.setBackground(new java.awt.Color(0, 102, 255));
        jButton_Check.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Check.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Check.setText("Check");
        jButton_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CheckActionPerformed(evt);
            }
        });

        txt_NgayDi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NgayDi.setText("2021-2-12");

        txt_NgayDen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NgayDen.setText("2021-2-2");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Thời gian:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("->");

        javax.swing.GroupLayout jPanelThongTinKhachHangLayout = new javax.swing.GroupLayout(jPanelThongTinKhachHang);
        jPanelThongTinKhachHang.setLayout(jPanelThongTinKhachHangLayout);
        jPanelThongTinKhachHangLayout.setHorizontalGroup(
            jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinKhachHangLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMaPhieuDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelThongTinKhachHangLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelThongTinKhachHangLayout.createSequentialGroup()
                        .addComponent(txt_NgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_NgayDi, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addComponent(txt_DiaChiKhachHang)
                    .addComponent(txt_SDT_KH)
                    .addComponent(txt_MaSoThueKH)
                    .addComponent(txt_HoTenKH)
                    .addGroup(jPanelThongTinKhachHangLayout.createSequentialGroup()
                        .addComponent(txt_MaKH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Check)))
                .addGap(25, 25, 25))
            .addGroup(jPanelThongTinKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelThongTinKhachHangLayout.setVerticalGroup(
            jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinKhachHangLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Check))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_HoTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaSoThueKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_SDT_KH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_DiaChiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanelThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelMaPhieuDat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTable_DsPhongDaChon.setBackground(new java.awt.Color(85, 163, 255));
        jTable_DsPhongDaChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_DsPhongDaChon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DsPhongDaChonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DsPhongDaChon);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Danh sách phòng:");

        javax.swing.GroupLayout jPanelNenFrameLayout = new javax.swing.GroupLayout(jPanelNenFrame);
        jPanelNenFrame.setLayout(jPanelNenFrameLayout);
        jPanelNenFrameLayout.setHorizontalGroup(
            jPanelNenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNenFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelThongTinKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelNenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNenFrameLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelThongTinPhong2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelNenFrameLayout.setVerticalGroup(
            jPanelNenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNenFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelThongTinKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelNenFrameLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelThongTinPhong2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNenFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelNenFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    public static String chuanHoa(String st, KhachHang khach) {
        st = st.trim();
        st = st.replaceAll("\\s+", " ");
        String[] temp = st.split(" ");
        st = "";
        String ho = "", ten = "";
        if (temp.length > 1) {

            for (int i = 0; i < temp.length; i++) {
                st += temp[i].substring(0, 1).toUpperCase() + temp[i].substring(1).toLowerCase();

                if (i < temp.length - 1) {
                    ho = st;
                    st += " ";
                } else if (i == temp.length - 1) {
                    ten += temp[i].substring(0, 1).toUpperCase() + temp[i].substring(1).toLowerCase();
                }
            }

        } else {
            for (int i = 0; i < temp.length; i++) {
                st = temp[0].substring(0, 1).toUpperCase() + temp[i].substring(1).toLowerCase();
            }
        }
        khach.setHo(ho);
        khach.setTen(ten);
        System.out.println("HO+ ten:" + ho + "  -  " + ten);
        return st;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        String sDT = txt_SDT_KH.getText().toString().trim();
        String cmnd = txt_MaKH.getText().toString().trim();
        String hoten = txt_HoTenKH.getText().toString().trim();
        String masothue = txt_MaSoThueKH.getText().toString().trim();
        String diachi = txt_DiaChiKhachHang.getText().toString().trim();
//        String mau = "[0-9]{9,10}";
//        if (cmnd.matches(mau) == false) {
//
//            txt_MaKH.requestFocus();
//            return;
//        }
//        mau = "[0-9]{10,11}";
//        if (sDT.matches(mau) == false) {
//
//            jLabelThongBao.setText("SDT khong hop le!");
//            txt_SDT_KH.requestFocus();
//            return;
//        }
////cmnd
//        mau = "^\\p{L}+[\\p{L}\\p{Z}\\p{P}]{1,20}";
//        if (hoten.equals("") || hoten.matches(mau) == false) {
//
//            jLabelThongBao.setText("Ho Ten Khach Hnag Khong Hop LE !");
//            txt_HoTenKH.requestFocus();
//            return;
//        }
        
        KhachHang kh = new KhachHang();
        hoten = chuanHoa(hoten, kh);
//        mau = "[0-9]{5,10}";
//        if (masothue.matches(mau) == false) {
//            jLabelThongBao.setText("Ma so thue khach hnag Khong hop le");
//            txt_MaSoThueKH.requestFocus();
//            return;
//        }
        PhieuThue phieu = new PhieuThue();
        //============== tìm xem mã Khách hàng đã có chưa =================

        khachThuePhongNay = DatThuePhongModify.TimKhach(cmnd);
        if (khachThuePhongNay == null) {
            khachThuePhongNay = new KhachHang(cmnd, kh.getHo(), kh.getTen(), diachi, sDT, masothue);
            DatThuePhongModify.ThemKhachVaoDB(khachThuePhongNay);
        } else {
            txt_MaKH.setText(khachThuePhongNay.getCMND());
            txt_HoTenKH.setText(khachThuePhongNay.getHo() + " " + khachThuePhongNay.getTen());
            txt_SDT_KH.setText(khachThuePhongNay.getSDT());
            txt_DiaChiKhachHang.setText(khachThuePhongNay.getDiaChi());
            txt_MaSoThueKH.setText(khachThuePhongNay.getMaSoThue());
            txt_SDT_KH.setText(khachThuePhongNay.getSDT());
        }

        phieu.setMaKH(khachThuePhongNay.getCMND());
        phieu.setMaNV(nvDangTruc.getMaNV());
        phieu.setMaPD(maPhieuDat);
        //=======================================Tạo phiếu thuê================================================
        if (DatThuePhongModify.ThemPhieuThueVaoDB(phieu) == false) {
            jLabelThongBao.setText("Tạo Phiếu Thuê thất bại! vui lòng kiểm tra lại thông tin");
            return;
        }
        Date dateDen = dsPhong.dsCTDat.get(0).getNgayDen() , dateDi =dsPhong.dsCTDat.get(0).getNgayDen();
        String ngayDen = txt_NgayDen.getText().toString().trim();
        String ngayDi = txt_NgayDi.getText().toString().trim();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        try {
            dateDen = Date.valueOf(ngayDen);
            dateDi = Date.valueOf(ngayDi);
        } catch (Exception e) {
            jLabelThongBao.setText("Ngày sai! Không chuyển ngày được!");
            return;
        }
        // ============================TẠo Phieu thue thành công -> tạo Chi tiết Thuê  ==========================================
        Phong pho;
        CTThue ctthue;
        for (CTPhieuDat phd: dsPhong.dsCTDat ){
            ctthue = new CTThue(phieu.getMaPT(), phd.getMaPhong(), dateDen, dateDi);
            if (DatThuePhongModify.ThemCTThueVaoDB(ctthue) == true) {

                JOptionPane.showMessageDialog(null, "Lập phiếu thuê thành công!", "Thông Báo", PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Lập phiếu thuê Thất Bại!", "Thông Báo", WARNING_MESSAGE);
            }
            jLabelThongBao.setText("");
            // cập nhật cái phong này trên sql, trên sơ đồ phòng ở frame Quản lý phòng và trên Panel Thông tin Thuê phòng được tạo ở Frame Quản lý phòng
            pho = RoomModify.TimPhong(ctthue.getMaPhong(), danhSachPhongTrongSql);
            
            pho.setTrangThai("Thuê");            
            // cập nhật trong sql
            RoomModify.UpdatePhong(pho);
            // cập nhật thông tin khách hàng trên pannel Thông tin thuê phòng
        }



        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CheckActionPerformed
        // TODO add your handling code here:
        String maKH = txt_MaKH.getText().toString().trim();

    }//GEN-LAST:event_jButton_CheckActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DatThuePhongModify.HuyBoPhietDat(maPhieuDat);
        this.setVisible(false);
//        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable_DsPhongDaChonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DsPhongDaChonMouseClicked
        // TODO add your handling code here:
        
//        table_Click_Row = jTable_DsPhongDaChon.getSelectedRow();
//        if(table_Click_Row < dsPhong.size() && table_Click_Row >= 0)
//            btn_remove.setEnabled(true);
//        else
//            btn_remove.setEnabled(false);
    }//GEN-LAST:event_jTable_DsPhongDaChonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormXemPhieuDat_Va_ThuePhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormXemPhieuDat_Va_ThuePhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormXemPhieuDat_Va_ThuePhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormXemPhieuDat_Va_ThuePhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormXemPhieuDat_Va_ThuePhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_Check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelMaNhanVien;
    private javax.swing.JLabel jLabelMaPhieuDat;
    private javax.swing.JLabel jLabelThongBao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelNenFrame;
    private javax.swing.JPanel jPanelThongTinKhachHang;
    private javax.swing.JPanel jPanelThongTinPhong2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_DsPhongDaChon;
    private javax.swing.JTextField txt_DiaChiKhachHang;
    private javax.swing.JTextField txt_HoTenKH;
    private javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_MaSoThueKH;
    private javax.swing.JTextField txt_NgayDen;
    private javax.swing.JTextField txt_NgayDi;
    private javax.swing.JTextField txt_SDT_KH;
    // End of variables declaration//GEN-END:variables
}
