/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLy;

import PanelChiaSoDoPhong.OptionQuanLyPhong;
import Data.RoomModify;
import static Data.RoomModify.TimPhong;
import Data.DatThuePhongModify;
import PanelChiaSoDoPhong.PanelThongTinThuePhong;
import PanelChiaSoDoPhong.SoDoPhong;
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import qlks.CTDL.CTThue;
import qlks.CTDL.KhachHang;
import qlks.CTDL.NhanVien;
import qlks.CTDL.PhieuDat;
import qlks.CTDL.PhieuThue;
import qlks.CTDL.Phong;
import qlks.CTDL.ThongTinThuePhong;
import static qlks.QLKS.layKetNoi;

/**
 *
 * @author HUYENKUTE _ HIHI Moa Moa Chụt Chụt :*
 */
public class QuanLyPhong extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyNhanVien
     */
    private static ThongTinThuePhong thongtin = null;
    private static Phong phongDangChon;
    private static ArrayList<Phong> danhSachPhong;
    private static ArrayList<PhieuThue> danhSachPhieuThue;
    private static ArrayList<PhieuDat> danhSachPhieuDat;
    private int MaPhongDangChon;
    private KhachHang khachCuaPhongDangChon;
    public static SoDoPhong sodo;
    public static PanelThongTinThuePhong panelThongTinThuePhong;
    public static NhanVien nhanVienDangDangNhap = null;

    public QuanLyPhong(NhanVien nv) {
        nhanVienDangDangNhap =  nv;
        initComponents();
        danhSachPhong = RoomModify.layDanhSachPhong();
        danhSachPhieuDat = RoomModify.layDanhSachPhieuDat();
        danhSachPhieuThue = RoomModify.layDanhSachPhieuThue();
        // TẠO SƠ ĐỒ
        sodo = new SoDoPhong(danhSachPhong);
        sodo.setSize(520, 320);
        sodo.setLocation(0, 0);
        jPanelSoDoPhong.add(sodo);
        sodo.setVisible(true);
        // TẠO VÙNG THÔNG TIN THUÊ PHÒNG BÊN PHẢI
        panelThongTinThuePhong = new PanelThongTinThuePhong();
        panelThongTinThuePhong.setSize(592, 628);
        panelThongTinThuePhong.setLocation(0, 0);
        jPanelThongTinThuePhong.add(panelThongTinThuePhong);
        panelThongTinThuePhong.setVisible(true);
        // SET MÃ PHÒNG
        txt_MaPhong.setEditable(false);

    }
  
    public QuanLyPhong() {
        initComponents();
        danhSachPhong = RoomModify.layDanhSachPhong();
        danhSachPhieuDat = RoomModify.layDanhSachPhieuDat();
        danhSachPhieuThue = RoomModify.layDanhSachPhieuThue();
        sodo = new SoDoPhong(danhSachPhong);
        sodo.setSize(520, 320);
        sodo.setLocation(0, 0);
        jPanelSoDoPhong.add(sodo);
        sodo.setVisible(true);
        
        // TẠO VÙNG THÔNG TIN THUÊ PHÒNG BÊN PHẢI
        panelThongTinThuePhong = new PanelThongTinThuePhong();
        panelThongTinThuePhong.setSize(592, 628);
        panelThongTinThuePhong.setLocation(0, 0);
        jPanelThongTinThuePhong.add(panelThongTinThuePhong);
        panelThongTinThuePhong.setVisible(true);
        
        
        txt_MaPhong.setEditable(false);
//        jPanelSoDoPhong
//        LoadPhong();

    }

    private void LoadPhong() {
//        jPanelSoDoPhong.removeAll();
        for (Phong phong : danhSachPhong) {

        }

    }
    
    private String layDonGia(String maHP) {
        Connection kn = layKetNoi();
        try {
            CallableStatement c = kn.prepareCall("{call loadGIAHANGPHONG (?)}");
            c.setString(1, maHP);
            ResultSet rs = c.executeQuery();
            while (rs.next()) {
                return rs.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Phong = new javax.swing.ButtonGroup();
        jPanelNenFrame = new javax.swing.JPanel();
        jPanelThongTinPhong = new javax.swing.JPanel();
        jButtonCapNhat = new javax.swing.JButton();
        jPanelSoDoPhong = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel_ThongTinPhongDangXem = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_MaPhong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_GiaPhong = new javax.swing.JLabel();
        jLabel_HangPHong = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanelThongTinThuePhong = new javax.swing.JPanel();

        setTitle("Quản Lý Phòng");
        setBackground(new java.awt.Color(153, 153, 255));
        setResizable(false);

        jPanelNenFrame.setBackground(new java.awt.Color(102, 153, 255));
        jPanelNenFrame.setMinimumSize(new java.awt.Dimension(1200, 600));
        jPanelNenFrame.setPreferredSize(new java.awt.Dimension(1200, 620));

        jPanelThongTinPhong.setBackground(new java.awt.Color(153, 204, 255));
        jPanelThongTinPhong.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Thông tin phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 51))); // NOI18N
        jPanelThongTinPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelThongTinPhong.setPreferredSize(new java.awt.Dimension(560, 580));

        jButtonCapNhat.setBackground(new java.awt.Color(50, 89, 255));
        jButtonCapNhat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCapNhat.setText("CẬP NHẬT");
        jButtonCapNhat.setEnabled(false);
        jButtonCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCapNhatActionPerformed(evt);
            }
        });

        jPanelSoDoPhong.setBackground(new java.awt.Color(0, 0, 102));
        jPanelSoDoPhong.setPreferredSize(new java.awt.Dimension(522, 320));
        jPanelSoDoPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSoDoPhongMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSoDoPhongLayout = new javax.swing.GroupLayout(jPanelSoDoPhong);
        jPanelSoDoPhong.setLayout(jPanelSoDoPhongLayout);
        jPanelSoDoPhongLayout.setHorizontalGroup(
            jPanelSoDoPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelSoDoPhongLayout.setVerticalGroup(
            jPanelSoDoPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(51, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 144, 109));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 131, 198));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel7.setText("Phòng đang được thuê");

        jLabel8.setText("Phòng chưa dọn");

        jLabel9.setText("Phòng chưa sửa chữa");

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel10.setText("Phòng trống");

        jPanel6.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel22.setText("Phòng đã đặt");

        jPanel_ThongTinPhongDangXem.setBackground(new java.awt.Color(153, 204, 255));
        jPanel_ThongTinPhongDangXem.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Hạng phòng:");

        txt_MaPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_MaPhong.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mã phòng:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Giá phòng:");

        lbl_GiaPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_GiaPhong.setForeground(new java.awt.Color(255, 22, 0));
        lbl_GiaPhong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_GiaPhong.setText("000,000,000");

        jLabel_HangPHong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_HangPHong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_HangPHong.setText(" ");

        javax.swing.GroupLayout jPanel_ThongTinPhongDangXemLayout = new javax.swing.GroupLayout(jPanel_ThongTinPhongDangXem);
        jPanel_ThongTinPhongDangXem.setLayout(jPanel_ThongTinPhongDangXemLayout);
        jPanel_ThongTinPhongDangXemLayout.setHorizontalGroup(
            jPanel_ThongTinPhongDangXemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ThongTinPhongDangXemLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_ThongTinPhongDangXemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ThongTinPhongDangXemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ThongTinPhongDangXemLayout.createSequentialGroup()
                        .addComponent(txt_MaPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_HangPHong, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_GiaPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel_ThongTinPhongDangXemLayout.setVerticalGroup(
            jPanel_ThongTinPhongDangXemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ThongTinPhongDangXemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ThongTinPhongDangXemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_MaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_HangPHong))
                .addGap(16, 16, 16)
                .addGroup(jPanel_ThongTinPhongDangXemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_GiaPhong))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText(" CHỌN PHÒNG: ");

        javax.swing.GroupLayout jPanelThongTinPhongLayout = new javax.swing.GroupLayout(jPanelThongTinPhong);
        jPanelThongTinPhong.setLayout(jPanelThongTinPhongLayout);
        jPanelThongTinPhongLayout.setHorizontalGroup(
            jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                        .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                                .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(27, 27, 27))
                                        .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(126, 126, 126))))
                                .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addContainerGap(60, Short.MAX_VALUE))))
                            .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                        .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_ThongTinPhongDangXem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelSoDoPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                            .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThongTinPhongLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelThongTinPhongLayout.setVerticalGroup(
            jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel_ThongTinPhongDangXem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSoDoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCapNhat)
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)))
                    .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                        .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelThongTinThuePhong.setBackground(new java.awt.Color(153, 204, 255));
        jPanelThongTinThuePhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelThongTinThuePhong.setPreferredSize(new java.awt.Dimension(560, 580));

        javax.swing.GroupLayout jPanelThongTinThuePhongLayout = new javax.swing.GroupLayout(jPanelThongTinThuePhong);
        jPanelThongTinThuePhong.setLayout(jPanelThongTinThuePhongLayout);
        jPanelThongTinThuePhongLayout.setHorizontalGroup(
            jPanelThongTinThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        jPanelThongTinThuePhongLayout.setVerticalGroup(
            jPanelThongTinThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelNenFrameLayout = new javax.swing.GroupLayout(jPanelNenFrame);
        jPanelNenFrame.setLayout(jPanelNenFrameLayout);
        jPanelNenFrameLayout.setHorizontalGroup(
            jPanelNenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNenFrameLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanelThongTinPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelThongTinThuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelNenFrameLayout.setVerticalGroup(
            jPanelNenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNenFrameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelNenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelThongTinPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addComponent(jPanelThongTinThuePhong, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelNenFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNenFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCapNhatActionPerformed
        // TODO add your handling code here:
        OptionQuanLyPhong op = new OptionQuanLyPhong(phongDangChon, sodo);
        op.thongtin = this.thongtin;
        repaint();
        
        op.setVisible(true);
        op.setFocusable(true);
        
    }//GEN-LAST:event_jButtonCapNhatActionPerformed
    
    
    private void jPanelSoDoPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSoDoPhongMouseClicked
        // TODO add your handling code here:
        
        MaPhongDangChon = sodo.getRoomIdFromPosition(evt.getPoint());
        
        panelThongTinThuePhong.MaPhongDangChon = this.MaPhongDangChon;   // truyền mã phòng sang pannel thông tin      
        panelThongTinThuePhong.hienThi(); // load ds dv da su dung cua phong dang chon
        panelThongTinThuePhong.repaint();
        
        System.out.println("Ma Phong click: " + MaPhongDangChon);
        if (MaPhongDangChon == -1) {

            jButtonCapNhat.setEnabled(false);
            return;
        }
        //===== RESET thông tin trên panel THông Tin ở bên Phải ======================
        panelThongTinThuePhong.giaPhong = 0;
        panelThongTinThuePhong.ResetThongTinThuePhong();
        phongDangChon = TimPhong(MaPhongDangChon, danhSachPhong);
        txt_MaPhong.setText(MaPhongDangChon+"");
        jLabel_HangPHong.setText(phongDangChon.getHangPhong());
        lbl_GiaPhong.setText((Integer.parseInt(layDonGia(phongDangChon.getHangPhong())) * 24) + "");
        panelThongTinThuePhong.ChoThanhToan(false);
        if(phongDangChon.getTrangThai().equals("Thuê"))
        {
            thongtin = RoomModify.TraCuuThongTinThuePhong(phongDangChon.getMaPhong());
            // nếu không tìm thấy thông tin thuê hiện tại
            if( thongtin == null)
            {
                JOptionPane.showMessageDialog(null, "Phòng ["+phongDangChon.getMaPhong()+"] đã quá hạn thuê", "thông báo", INFORMATION_MESSAGE);
                return;
            }
            panelThongTinThuePhong.UpdateThongTinThuePhong(thongtin);
            panelThongTinThuePhong.ChoThanhToan(true);
            panelThongTinThuePhong.MaPTCuaPhongDangChon = thongtin.phieuThue.getMaPT();
            panelThongTinThuePhong.repaint();
            jButtonCapNhat.setEnabled(false);
            
        }
        else if(phongDangChon.getTrangThai().equals("Đặt")){
            // nếu không tìm thấy thông tin thuê hiện tại
            thongtin = RoomModify.TraCuuThongTinDatPhong(phongDangChon.getMaPhong());
            panelThongTinThuePhong.UpdateThongTinThuePhong(thongtin);
            panelThongTinThuePhong.repaint();            
            jButtonCapNhat.setEnabled(false);
        }
        else{
            
            jButtonCapNhat.setEnabled(true);
        }
        System.out.println(MaPhongDangChon);
        jButtonCapNhat.setEnabled(true);
    }//GEN-LAST:event_jPanelSoDoPhongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Phong;
    private javax.swing.JButton jButtonCapNhat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_HangPHong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelNenFrame;
    private javax.swing.JPanel jPanelSoDoPhong;
    private javax.swing.JPanel jPanelThongTinPhong;
    private javax.swing.JPanel jPanelThongTinThuePhong;
    private javax.swing.JPanel jPanel_ThongTinPhongDangXem;
    private javax.swing.JLabel lbl_GiaPhong;
    private javax.swing.JTextField txt_MaPhong;
    // End of variables declaration//GEN-END:variables
}
