package QuanLy;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class QuanLyTienNghi extends javax.swing.JFrame {

    private Vector ds = null;
    private String tenTienNghi;

    public QuanLyTienNghi() {
        initComponents();
        setTitle("QUẢN LÝ TIỆN NGHI");
        khoiTaoTB();
        layDS();
        khoiTaoTXT();
        khoiTaoTB();
    }

    private void khoiTaoTB() {
        tb_maTN.setText(" ");
        tb_tenTienNghi.setText(" ");
    }

    private void khoiTaoTXT() {
        //reset
        txt_maTN.setText("");
        txt_tenTienNghi.setText("");
    }

    private void layDS() {
        DefaultTableModel dtm = (DefaultTableModel) table_DSTN.getModel();
        dtm.setNumRows(0);
        Connection kn = qlks.QLKS.layKetNoi();
        String sql = "select * from TIENNGHI";
        Vector vt;
        ds = new Vector();
        try {
            PreparedStatement ps = kn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                vt = new Vector();
                vt.add(rs.getString("MATN"));
                vt.add(rs.getString("TENTIENNGHI"));
                ds.add(vt);
                dtm.addRow(vt);
            }
            table_DSTN.setModel(dtm);
            rs.close();
            ps.close();
            kn.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyTienNghi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNenFrame = new javax.swing.JPanel();
        jPanelThongTinPhong = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_maTN = new javax.swing.JTextField();
        txt_tenTienNghi = new javax.swing.JTextField();
        tb_maTN = new javax.swing.JLabel();
        tb_tenTienNghi = new javax.swing.JLabel();
        jPanelThongTinPhong1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_DSTN = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanelThongTinPhong2 = new javax.swing.JPanel();
        them = new javax.swing.JButton();
        sua = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        thoat = new javax.swing.JButton();
        capnhat = new javax.swing.JButton();

        setTitle("Quản Lý Tiện Nghi");
        setBackground(new java.awt.Color(153, 153, 255));
        setResizable(false);

        jPanelNenFrame.setBackground(new java.awt.Color(102, 153, 255));
        jPanelNenFrame.setMinimumSize(new java.awt.Dimension(1200, 600));
        jPanelNenFrame.setPreferredSize(new java.awt.Dimension(950, 620));

        jPanelThongTinPhong.setBackground(new java.awt.Color(153, 204, 255));
        jPanelThongTinPhong.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Thông tin tiện nghi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 51))); // NOI18N
        jPanelThongTinPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelThongTinPhong.setPreferredSize(new java.awt.Dimension(560, 580));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mã tiện nghi:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tên tiện nghi:");

        tb_maTN.setForeground(new java.awt.Color(255, 0, 0));
        tb_maTN.setText("jLabel4");

        tb_tenTienNghi.setForeground(new java.awt.Color(255, 0, 0));
        tb_tenTienNghi.setText("jLabel4");

        javax.swing.GroupLayout jPanelThongTinPhongLayout = new javax.swing.GroupLayout(jPanelThongTinPhong);
        jPanelThongTinPhong.setLayout(jPanelThongTinPhongLayout);
        jPanelThongTinPhongLayout.setHorizontalGroup(
            jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThongTinPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txt_tenTienNghi, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tb_maTN, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tb_tenTienNghi, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_maTN, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );
        jPanelThongTinPhongLayout.setVerticalGroup(
            jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinPhongLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_maTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(tb_maTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tenTienNghi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_tenTienNghi)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jPanelThongTinPhong1.setBackground(new java.awt.Color(153, 204, 255));
        jPanelThongTinPhong1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Danh sách tiện nghi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 51))); // NOI18N
        jPanelThongTinPhong1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelThongTinPhong1.setPreferredSize(new java.awt.Dimension(560, 580));

        table_DSTN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tiện nghi", "Tên tiện nghi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_DSTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DSTNMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_DSTN);
        if (table_DSTN.getColumnModel().getColumnCount() > 0) {
            table_DSTN.getColumnModel().getColumn(0).setMinWidth(100);
            table_DSTN.getColumnModel().getColumn(0).setPreferredWidth(500);
            table_DSTN.getColumnModel().getColumn(0).setMaxWidth(100);
            table_DSTN.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SER_247.png"))); // NOI18N

        javax.swing.GroupLayout jPanelThongTinPhong1Layout = new javax.swing.GroupLayout(jPanelThongTinPhong1);
        jPanelThongTinPhong1.setLayout(jPanelThongTinPhong1Layout);
        jPanelThongTinPhong1Layout.setHorizontalGroup(
            jPanelThongTinPhong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinPhong1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThongTinPhong1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(16, 16, 16))
        );
        jPanelThongTinPhong1Layout.setVerticalGroup(
            jPanelThongTinPhong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinPhong1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jPanelThongTinPhong2.setBackground(new java.awt.Color(153, 204, 255));
        jPanelThongTinPhong2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Hành động", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 51))); // NOI18N
        jPanelThongTinPhong2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelThongTinPhong2.setPreferredSize(new java.awt.Dimension(560, 580));

        them.setBackground(new java.awt.Color(51, 153, 255));
        them.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/THEM.png"))); // NOI18N
        them.setText("THÊM");
        them.setToolTipText("Click để thêm tiện nghi!");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        sua.setBackground(new java.awt.Color(51, 153, 255));
        sua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/SUA.png"))); // NOI18N
        sua.setText("SỬA");
        sua.setToolTipText("Click để chỉnh sửa tên tiện nghi!");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        xoa.setBackground(new java.awt.Color(51, 153, 255));
        xoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/XOA.png"))); // NOI18N
        xoa.setText("XÓA");
        xoa.setToolTipText("Click để xóa tiện nghi!");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        thoat.setBackground(new java.awt.Color(51, 153, 255));
        thoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/EXIT.png"))); // NOI18N
        thoat.setText("THOÁT");
        thoat.setToolTipText("Click để thoát quản lí tiện nghi!");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        capnhat.setBackground(new java.awt.Color(153, 204, 255));
        capnhat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        capnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/hinh/RESET.png"))); // NOI18N
        capnhat.setToolTipText("Click để reset!!");
        capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelThongTinPhong2Layout = new javax.swing.GroupLayout(jPanelThongTinPhong2);
        jPanelThongTinPhong2.setLayout(jPanelThongTinPhong2Layout);
        jPanelThongTinPhong2Layout.setHorizontalGroup(
            jPanelThongTinPhong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinPhong2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelThongTinPhong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThongTinPhong2Layout.createSequentialGroup()
                        .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelThongTinPhong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelThongTinPhong2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanelThongTinPhong2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(sua, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))))
                    .addGroup(jPanelThongTinPhong2Layout.createSequentialGroup()
                        .addComponent(thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelThongTinPhong2Layout.setVerticalGroup(
            jPanelThongTinPhong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinPhong2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelThongTinPhong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelNenFrameLayout = new javax.swing.GroupLayout(jPanelNenFrame);
        jPanelNenFrame.setLayout(jPanelNenFrameLayout);
        jPanelNenFrameLayout.setHorizontalGroup(
            jPanelNenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNenFrameLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelNenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelThongTinPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelThongTinPhong2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelThongTinPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNenFrameLayout.setVerticalGroup(
            jPanelNenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNenFrameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelNenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelNenFrameLayout.createSequentialGroup()
                        .addComponent(jPanelThongTinPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelThongTinPhong2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelThongTinPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNenFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNenFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean checkMaTN(String maTN) {
        boolean kt = true;
        if (maTN.equals("") == true) {
            tb_maTN.setText("Mã tiện nghi không được bỏ trống!");
            return false;
        } else {
            String mau = "[A-Za-z0-9]{1,10}";
            if (maTN.matches(mau) == false) {
                tb_maTN.setText("Mã tiện nghi không hợp lệ!");
                return false;
            }
        }
        try {
            Connection kn = qlks.QLKS.layKetNoi();
            PreparedStatement ps = kn.prepareStatement("select * from TIENNGHI where MATN = '" + maTN + "'");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                kt = false;
            }
            rs.close();
            ps.close();
            kn.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyTienNghi.class.getName()).log(Level.SEVERE, null, ex);
        }
        tb_maTN.setText("");
        if (kt == false) {
            tb_maTN.setText("Mã tiện nghi đã tồn tại!");
        }
        return kt;
    }

    private boolean checkTenTienNghi(String tenTienNghi) {
        if (tenTienNghi.equals("") == true) {
            tb_tenTienNghi.setText("Tên tiện nghi không được để trống!");
            return false;
        } else {
            String mau = "^\\p{L}+[\\p{L}\\p{Z}\\p{P}]{1,20}";
            if (tenTienNghi.matches(mau) == false) {
                tb_tenTienNghi.setText("Tên tiện nghi không hợp lệ!");
                return false;
            }
        }
        tb_tenTienNghi.setText("");
        return true;
    }

    private void them(String maTN, String tenTienNghi) {
        Connection kn = qlks.QLKS.layKetNoi();
        try {
            PreparedStatement ps = kn.prepareStatement("INSERT INTO TIENNGHI VALUES (?,?)");
            ps.setString(1, maTN);
            ps.setString(2, tenTienNghi);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyTienNghi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        Boolean kt = true;
        String maTN = txt_maTN.getText();
        String tenTienNghi = txt_tenTienNghi.getText();
        if (checkMaTN(maTN) == false) {
            kt = false;
        }
        if (checkTenTienNghi(tenTienNghi) == false) {
            kt = false;
        }
        if (kt == true) {
            them(maTN, tenTienNghi);
            layDS();
            khoiTaoTXT();
            khoiTaoTB();
            JOptionPane.showMessageDialog(this, "Thêm tiện nghi thành công!");
        }
    }//GEN-LAST:event_themActionPerformed
    private void sua(String maTN, String tenTienNghi) {

        Connection kn = qlks.QLKS.layKetNoi();
        try {
            PreparedStatement ps = kn.prepareStatement("UPDATE TIENNGHI SET TENTIENNGHI = ? WHERE MATN = ?");
            ps.setString(2, maTN);
            ps.setString(1, tenTienNghi);
            ps.executeUpdate();
            ps.close();
            kn.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyTienNghi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
        Boolean kt = true;
        String maTN = txt_maTN.getText();
        String tenTienNghi = txt_tenTienNghi.getText();
        //txt_maTN.setEditable(false);
        if (tenTienNghi.equals(this.tenTienNghi)) {
            JOptionPane.showMessageDialog(this, "Bạn không thay đổi gì cả!");
        } else {
            if (maTN.equals("") == true) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn thông tin cần sửa!");
                kt = false;
            }
            if (checkTenTienNghi(tenTienNghi) == false) {
                kt = false;
            }
            if (kt == true) {
                sua(maTN, tenTienNghi);
                layDS();
                khoiTaoTXT();
                khoiTaoTB();
                txt_maTN.setEditable(true);
                JOptionPane.showMessageDialog(this, "Sửa tiện nghi thành công!");
            }
        }


    }//GEN-LAST:event_suaActionPerformed
    private void xoa(String maTN) {
        Connection kn = qlks.QLKS.layKetNoi();
        String sql = "delete from TIENNGHI where MATN = ?";
        try {
            PreparedStatement ps = kn.prepareStatement(sql);
            ps.setString(1, maTN);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyTienNghi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean kiemTraTienNghi(String maTN) {
        String temp;
        boolean kt = false;
        Connection kn = qlks.QLKS.layKetNoi();
        if (maTN.equals("") == true) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã tiện nghi để xóa!");
        } else {
            try {
                PreparedStatement ps = kn.prepareStatement("select * from TIENNGHI");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    temp = rs.getString("MATN");
                    if (temp.equals(maTN) == true) {
                        kt = true;
                        break;
                    }
                }
                rs.close();
                ps.close();
                kn.close();
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyTienNghi.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (kt == false) {
                JOptionPane.showMessageDialog(this, "Tiện nghi này không tồn tại!");
            } else {
                if (kt == true) try {
                    kn = qlks.QLKS.layKetNoi();
                    PreparedStatement ps = kn.prepareStatement("select * from CT_TIENNGHI where MATN = '" + maTN + "'");
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        kt = false;
                    }
                    rs.close();
                    ps.close();
                    kn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (kt == false) {
                    JOptionPane.showMessageDialog(this, "Không thể xóa tiện nghi này!");
                }
            }
        }
        return kt;
    }
    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        // TODO add your handling code here:
        String maTN = txt_maTN.getText();
        String tenTienNghi = txt_tenTienNghi.getText();
        boolean kt = true;
        kt = kiemTraTienNghi(maTN);
        if (kt == true) {
            //xoa.setToolTipText("Click để xóa tiện nghi! ");
            int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa tiện"
                    + " nghi không", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION);
            if (selected == JOptionPane.YES_NO_OPTION) {
                xoa(maTN);
                layDS();
                khoiTaoTXT();
                khoiTaoTB();
                txt_tenTienNghi.setEditable(false);
                JOptionPane.showMessageDialog(this, "Xóa tiện nghi thành công!");
            }
        }
    }//GEN-LAST:event_xoaActionPerformed

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatActionPerformed
        // TODO add your handling code here:
        //thoat.setToolTipText("Click để thoát quản lí tiện nghi! ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát chương"
                + " trình không", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            this.dispose(); //Chỉ đóng form hiện hành
        }
    }//GEN-LAST:event_thoatActionPerformed
    private void reset() {
        txt_maTN.setText("");
        txt_tenTienNghi.setText("");;
        txt_maTN.requestFocus();
    }
    private void capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatActionPerformed
        // TODO add your handling code here:
        reset();
        khoiTaoTB();
    }//GEN-LAST:event_capnhatActionPerformed

    private void table_DSTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DSTNMouseClicked
        // TODO add your handling code here:
        int i = table_DSTN.getSelectedRow();
        TableModel model = table_DSTN.getModel();
        txt_maTN.setText(model.getValueAt(i, 0).toString());
        txt_tenTienNghi.setText(model.getValueAt(i, 1).toString());
    }//GEN-LAST:event_table_DSTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyTienNghi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyTienNghi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyTienNghi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTienNghi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyTienNghi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton capnhat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelNenFrame;
    private javax.swing.JPanel jPanelThongTinPhong;
    private javax.swing.JPanel jPanelThongTinPhong1;
    private javax.swing.JPanel jPanelThongTinPhong2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sua;
    private javax.swing.JTable table_DSTN;
    private javax.swing.JLabel tb_maTN;
    private javax.swing.JLabel tb_tenTienNghi;
    private javax.swing.JButton them;
    private javax.swing.JButton thoat;
    private javax.swing.JTextField txt_maTN;
    private javax.swing.JTextField txt_tenTienNghi;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
